# Generated by Django 3.0.6 on 2020-06-16 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('ssn', models.IntegerField(max_length=9)),
                ('zipcode', models.CharField(max_length=5)),
                ('country', models.CharField(default='United States of America', max_length=50)),
                ('city', models.CharField(max_length=30)),
                ('cellPhone', models.IntegerField(max_length=15)),
                ('homePhone', models.IntegerField(max_length=15)),
                ('email', models.CharField(max_length=30)),
                ('location', models.CharField(max_length=30)),
                ('refer', models.CharField(default='No Refer', max_length=30)),
                ('sources', models.CharField(default='Individual', max_length=30)),
                ('notes', models.CharField(max_length=200)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=10)),
                ('newsLetter', models.TextField()),
                ('created_on', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'student',
                'verbose_name_plural': 'students',
                'ordering': ['created_on'],
            },
        ),
    ]
