# Generated by Django 3.0.6 on 2020-06-16 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wiawdp', '0002_auto_20200616_1642'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CareerPathway',
            new_name='WIAWDP',
        ),
    ]
