# Generated by Django 3.0.6 on 2020-06-14 16:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('department', models.CharField(choices=[('administration', 'Administration'), ('admission', 'Admission'), ('marketing', 'Marketing'), ('sales', 'Sales'), ('humanresources', 'Human Resources'), ('careerservices', 'Career Services'), ('finance', 'Finannce'), ('staff', 'Staff'), ('faculty', 'Faculty')], max_length=32)),
                ('role', models.CharField(choices=[('student', 'Student'), ('prospective', 'Prospective '), ('avtechemployee', 'AVTech Employee'), ('instructor', 'Instructor'), ('instructor_contractor', 'Adjunct Instructor')], max_length=32)),
            ],
            options={
                'permissions': (('can_list_employees', 'List All Employees'),),
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website', models.URLField(blank=True)),
                ('picture', models.ImageField(blank=True, upload_to='profile_images')),
                ('role', models.CharField(choices=[('student', 'Student'), ('prospective', 'Prospective '), ('avtechemployee', 'AVTech Employee'), ('instructor', 'Instructor'), ('instructor_contractor', 'Adjunct Instructor')], max_length=32)),
                ('avtech_department', models.CharField(choices=[('administration', 'Administration'), ('admission', 'Admission'), ('marketing', 'Marketing'), ('sales', 'Sales'), ('humanresources', 'Human Resources'), ('careerservices', 'Career Services'), ('finance', 'Finannce'), ('staff', 'Staff'), ('faculty', 'Faculty')], max_length=32)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
