# Generated by Django 3.0.6 on 2020-06-14 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employee',
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'permissions': (('can_list_userprofiles', 'List All User Profiles'),)},
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('prospective', 'Prospective '), ('avtechemployee', 'AVTech Employee'), ('instructor', 'Instructor'), ('instructor_contractor', 'Instructor - Adjunct'), ('vendor_institutional', 'Vendor - Institutional'), ('vendor_government', 'Vendor - Government'), ('vendor_business', 'Vendor - Business')], max_length=32),
        ),
    ]
